In [ ]:
# My first Homework. A game made in Python

In [1]:
from numpy import array, zeros

from random import randint

In [2]:
display = array([[1,2,3],[4,5,6],[7,8,9]])

print(display)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
field = array([[0,0,0],[0,0,0],[0,0,0]])

print(field)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
k = 0

while k == 0:
    nr_of_zeros = 0
    for i in range(3):
        for j in range(3):
            if field[j][i] == 0:
                nr_of_zeros += 1
    if nr_of_zeros == 0:
        print("TIE! \n")
        break
    i = 0
    while i == 0:
        z = int(input("Input number of fields! \n"))
        if z >= 1 and z < 10:
             if z == 1:
                 x = 0
                 y = 0
             elif z == 2:
                 x = 1
                 y = 0
             elif z == 3:
                 x = 2
                 y = 0
             elif z == 4:
                 x = 0
                 y = 1
             elif z == 5:
                 x = 1
                 y = 1
             elif z == 6:
                 x = 2
                 y = 1
             elif z == 7:
                 x = 0
                 y = 2
             elif z == 8:
                 x = 1
                 y = 2
             elif z == 9:
                 x = 2
                 y = 2
             if field[y][x] == 0:
                 field[y][x] = 1
                 break
             else:
                 print("Occupied!")
                 continue
        else:
            print("Wrong!")
    print("Human's turn!")
    print(field)
    no_1 = 0
    no_2 = 0
    i = 0
    j = 0
    for i in range(3):
        no_1 = 0
        no_2 = 0
        for j in range(3):
            if field[j][i] == 1:
                no_1 += 1
            elif field[j][i] == 2:
                no_2 += 1
        if no_1 == 3:
            print("Winner is Human!")
            break
        elif no_2 == 3:
            print("Winner is Computer!")
            break
    if no_1 == 3 or no_2 == 3:
        break
    no_1 = 0
    no_2 = 0
    i = 0
    j = 0
    for j in range(3):
        no_1 = 0
        no_2 = 0
        for i in range(3):
            if field[j][i] == 1:
                no_1 += 1
            elif field[j][i] == 2:
                no_2 += 1
        if no_1 == 3:
            print("Winner is Human!")
            break
        elif no_2 == 3:
            print("Winner is Computer!")
            break
    if no_1 == 3 or no_2 == 3:
        break
    no_1 = 0
    no_2 = 0
    i = 0
    for i in range(3):
        if field[i][i] == 1:
            no_1 += 1
        elif field[i][i] == 2:
            no_2 += 1
    if no_1 == 3:
        print("Winner is Human!")
        break
    elif no_2 == 3:
        print("Winner is Computer!")
        break
    no_1 = 0
    no_2 = 0
    i = 0
    for i in range(3):
        if field[2 - i][i] == 1:
            no_1 += 1
        elif field[2 - i][i] == 2:
            no_2 += 1
    if no_1 == 3:
        print("Winner is Human!")
        break
    elif no_2 == 3:
        print("Winner is Computer!")
        break

    nr_of_zeros = 0
    for i in range(3):
        for j in range(3):
            if field[j][i] == 0:
                nr_of_zeros += 1
    if nr_of_zeros == 0:
        print("Tie!")
        break
    
    i = 0
    while i == 0:
        x = randint(0,2)
        y = randint(0,2)
        if field[y][x] == 0:
            field[y][x] = 2
            break
    print("Computer's turn!")
    print(field)

    no_1 = 0
    no_2 = 0
    i = 0
    j = 0
    for i in range(3):
        no_1 = 0
        no_2 = 0
        for j in range(3):
            if field[j][i] == 1:
                no_1 += 1
            elif field[j][i] == 2:
                no_2 += 1
        if no_1 == 3:
            print("Winner is Human!")
            break
        elif no_2 == 3:
            print("Winner is Computer!")
            break
    if no_1 == 3 or no_2 == 3:
        break
    no_1 = 0
    no_2 = 0
    i = 0
    j = 0
    for j in range(3):
        no_1 = 0
        no_2 = 0
        for i in range(3):
            if field[j][i] == 1:
                no_1 += 1
            elif field[j][i] == 2:
                no_2 += 1
        if no_1 == 3:
            print("Winner is Human!")
            break
        elif no_2 == 3:
            print("Winner is Computer!")
            break
    if no_1 == 3 or no_2 == 3:
        break
    no_1 = 0
    no_2 = 0
    i = 0
    for i in range(3):
        if field[i][i] == 1:
            no_1 += 1
        elif field[i][i] == 2:
            no_2 += 1
    if no_1 == 3:
        print("Winner is Human!")
        break
    elif no_2 == 3:
        print("Winner is Computer!")
        break
    no_1 = 0
    no_2 = 0
    i = 0
    for i in range(3):
        if field[2 - i][i] == 1:
            no_1 += 1
        elif field[2 - i][i] == 2:
            no_2 += 1
    if no_1 == 3:
        print("Winner is Human!")
        break
    elif no_2 == 3:
        print("Winner is Computer!")
        break

Input number of fields! 
5
Human's turn!
[[0 0 0]
 [0 1 0]
 [0 0 0]]
Computer's turn!
[[0 0 0]
 [0 1 0]
 [0 2 0]]
Input number of fields! 
1
Human's turn!
[[1 0 0]
 [0 1 0]
 [0 2 0]]
Computer's turn!
[[1 0 0]
 [2 1 0]
 [0 2 0]]
Input number of fields! 
9
Human's turn!
[[1 0 0]
 [2 1 0]
 [0 2 1]]
pobjednik je igrac!
